### ISSUE TITLE
Write data model blueprint for example project

### ISSUE THREAD

**Issue by vincentlortie** [seeqbio/django-prepop#1]
## Context
Example apps give concrete code examples and are a great tool to facilitate testing. In this ticket, we want to craft the data model which will be behind our example project. Our general project theme is a Blog app. 

We want our data model to be intuitive and easy to understand. However, we also want to showcase how this package can help represent complex relationships.

## Goals
1. Create basic models and their attributes (as a comment in this ticket).
2. Create meaningful relationships between different models.

**Comment by vincentlortie** [comment]
Here is a first pass, focusing on the relationships between models, keeping individual models lightweight.

```
# Django auth user
class User
  pass

class Author(User)
  pass

class Post:
  title: string
  author: Author
  content: string

class Comment
  author: User
  content: string
  post: Post
  # Used to represent comment threads
  parent: Comment 

class Favorite
  post: Post
  user: User
```

@amirkdv let me know if there are any low hanging fruits I may have missed, or other ideas to expand.

**Comment by amirkdv** [comment]
Thanks @vincentlortie!

1. I think this covers a lot of use cases we'd want to show. Maybe the quickstart example is only about Users and Posts. Then a more advanced example would involve Comments and Comment threads?
1. Maybe for simplification we could drop Author and just use User as the FK in Post?
1. What's the value-add of the Favorite model? i.e. what use case is it showcasing that other models wouldn't? From what I can tell, the Favorite -> User FK is similar in structure to Comment -> User and Comment -> Post.

**Comment by vincentlortie** [comment]
I agree with point 1. and 2.

As for 3, for lack of a better term, I added it to give some "meat" to the data model. This does not seem necessary. We can drop it and proceed forward with the rest.

**Comment by vincentlortie** [comment]
@amirkdv Closing this ticket and will get started on #2
